# Generated by Django 3.1 on 2020-08-29 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='group',
            new_name='groupp',
        ),
    ]
